# Generated by Django 4.1.3 on 2022-11-20 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeProductApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=50)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stripe_module.item')),
            ],
        ),
    ]
