# Generated by Django 4.1.3 on 2022-11-21 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_module', '0004_orders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
